<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'threezerozero',
        'fivefivezero',
        'thumbnail'
    ];

    public function imageable()
    {
        return $this->morphTo();
    }

    public function delete()
    {
        Storage::delete(storage_path('app/public'). $this->threezerozero);
        Storage::delete(storage_path('app/public'). $this->fivefivezero);
        Storage::delete(storage_path('app/public'). $this->thumbnail);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
